language: generic
dist: trusty
sudo: false
env:
  global:
    - DEVKITARM=$HOME/devkitARM
addons:
  apt:
    packages:
      - gcc-multilib
      - linux-libc-dev
cache:
  apt: true
install:
  - pushd $HOME
  - travis_retry wget http://download.sourceforge.net/devkitpro/devkitARM_r46-x86_64-linux.tar.bz2
  - tar xf devkitARM*.tar.bz2
  - popd

matrix:
  include:
    - os: linux
      env: _="Build German"
      before_script:
        - mkdir build && cd build
        - cmake .. -GNinja
      script:
        - ninja
  allow_failures:
    - env: _="Formatting"
