gBerryDescriptionPart1_Cheri: @ 83CC740
	.string "Erblüht mit hübschen, zarten Blumen.$"

gBerryDescriptionPart2_Cheri: @ 83CC765
	.string "Diese knallrote BEERE ist sehr scharf.$"

gBerryDescriptionPart1_Chesto: @ 83CC789
	.string "Diese BEERE hat eine dicke Haut und$"

gBerryDescriptionPart2_Chesto: @ 83CC7AE
	.string "hartes Fruchtfleisch. Trocken!$"

gBerryDescriptionPart1_Pecha: @ 83CC7D6
	.string "Sehr süß und delikat.$"

gBerryDescriptionPart2_Pecha: @ 83CC7F0
	.string "Sehr zart. Vorsichtig anfassen!$"

gBerryDescriptionPart1_Rawst: @ 83CC815
	.string "Wenn die Blätter lang und wellig sind,$"

gBerryDescriptionPart2_Rawst: @ 83CC838
	.string "wird die BEERE sehr bitter.$"

gBerryDescriptionPart1_Aspear: @ 83CC85D
	.string "Diese harte BEERE ist sehr$"

gBerryDescriptionPart2_Aspear: @ 83CC881
	.string "saftig und sauer im Geschmack!$"

gBerryDescriptionPart1_Leppa: @ 83CC89A
	.string "Wächst langsamer als AMRENA und$"

gBerryDescriptionPart2_Leppa: @ 83CC8BE
	.string "andere. Je kleiner, desto delikater.$"

gBerryDescriptionPart1_Oran: @ 83CC8E2
	.string "Eine BEERE unterschiedlichsten Ge-$"

gBerryDescriptionPart2_Oran: @ 83CC90A
	.string "schmacks. Wächst an einem halben Tag.$"

gBerryDescriptionPart1_Persim: @ 83CC926
	.string "Liebt Sonnenlicht. Die BEERE$"

gBerryDescriptionPart2_Persim: @ 83CC948
	.string "wächst im Sonnenlicht sehr schnell.$"

gBerryDescriptionPart1_Lum: @ 83CC96D
	.string "Langsamer Wuchs. Wird sie liebevoll ge-$"

gBerryDescriptionPart2_Lum: @ 83CC991
	.string "pflegt, kann sie 2 BEEREN tragen.$"

gBerryDescriptionPart1_Sitrus: @ 83CC9B0
	.string "Eng verwandt mit SINEL. Diese große$"

gBerryDescriptionPart2_Sitrus: @ 83CC9D3
	.string "BEERE ist von rundem Geschmack.$"

gBerryDescriptionPart1_Figy: @ 83CC9F4
	.string "Die BEERE sieht angekaut aus. Sie ist$"

gBerryDescriptionPart2_Figy: @ 83CCA16
	.string "voller scharfer Substanzen.$"

gBerryDescriptionPart1_Wiki: @ 83CCA33
	.string "Die BEERE wächst unförmig,$"

gBerryDescriptionPart2_Wiki: @ 83CCA59
	.string "damit PKMN sie besser greifen können.$"

gBerryDescriptionPart1_Mago: @ 83CCA72
	.string "Die BEERE hat Ausbeulungen. Je mehr$"

gBerryDescriptionPart2_Mago: @ 83CCA95
	.string "Beulen, desto schmackhafter ist sie.$"

gBerryDescriptionPart1_Aguav: @ 83CCABB
	.string "Die Blume ist zart. Sie ist fähig,$"

gBerryDescriptionPart2_Aguav: @ 83CCAE3
	.string "ohne Licht wachsen zu können.$"

gBerryDescriptionPart1_Iapapa: @ 83CCB02
	.string "Die BEERE ist groß und sauer.$"

gBerryDescriptionPart2_Iapapa: @ 83CCB22
	.string "Sie braucht einen Tag zum Wachsen.$"

gBerryDescriptionPart1_Razz: @ 83CCB43
	.string "Diese rote BEERE schmeckt etwas$"

gBerryDescriptionPart2_Razz: @ 83CCB68
	.string "scharf. Sie wächst in nur 4 Stunden.$"

gBerryDescriptionPart1_Bluk: @ 83CCB8D
	.string "Die BEERE ist außen blau, verfärbt$"

gBerryDescriptionPart2_Bluk: @ 83CCBB3
	.string "sich im Mund aber schwarz.$"

gBerryDescriptionPart1_Nanab: @ 83CCBD5
	.string "Diese BEERE war die 7., die auf der$"

gBerryDescriptionPart2_Nanab: @ 83CCBF0
	.string "Welt entdeckt wurde. Sie ist süß.$"

gBerryDescriptionPart1_Wepear: @ 83CCC16
	.string "Die Blume ist klein und weiß. Angenehm$"

gBerryDescriptionPart2_Wepear: @ 83CCC3E
	.string "bitter und sauer zugleich.$"

gBerryDescriptionPart1_Pinap: @ 83CCC63
	.string "Wind und Kälte verträgt sie nicht.$"

gBerryDescriptionPart2_Pinap: @ 83CCC7F
	.string "Fruchtfleisch: Scharf. Haut: Sauer.$"

gBerryDescriptionPart1_Pomeg: @ 83CCCA6
	.string "Egal wie viel Wasser sie bekommt, sie$"

gBerryDescriptionPart2_Pomeg: @ 83CCCC2
	.string "trägt immer bis zu 6 BEEREN.$"

gBerryDescriptionPart1_Kelpsy: @ 83CCCE3
	.string "Eine Seltenheit. Geformt wie eine$"

gBerryDescriptionPart2_Kelpsy: @ 83CCD06
	.string "Wurzel. Hat eine große Blume.$"

gBerryDescriptionPart1_Qualot: @ 83CCD21
	.string "Liebt das Wasser. Wächst besonders$"

gBerryDescriptionPart2_Qualot: @ 83CCD43
	.string "gut in regenreichen Gegenden.$"

gBerryDescriptionPart1_Hondew: @ 83CCD65
	.string "Eine wertvolle und seltene BEERE.$"

gBerryDescriptionPart2_Hondew: @ 83CCD87
	.string "Sie ist sehr schmackhaft.$"

gBerryDescriptionPart1_Grepa: @ 83CCDAA
	.string "Die BEERE ist zart und von runder$"

gBerryDescriptionPart2_Grepa: @ 83CCDCB
	.string "Form. Aber sie ist unglaublich sauer!$"

gBerryDescriptionPart1_Tamato: @ 83CCDF2
	.string "Die Schärfe der BEERE verbrennt die$"

gBerryDescriptionPart2_Tamato: @ 83CCE14
	.string "Lippen. Sie braucht Zeit zum Wachsen.$"

gBerryDescriptionPart1_Cornn: @ 83CCE2B
	.string "Eine BEERE aus alten Zeiten. Wächst$"

gBerryDescriptionPart2_Cornn: @ 83CCE50
	.string "nur, wenn in großen Mengen gepflanzt.$"

gBerryDescriptionPart1_Magost: @ 83CCE71
	.string "Eine BEERE, die für ihren feinen, aus-$"

gBerryDescriptionPart2_Magost: @ 83CCE95
	.string "gewogenen Geschmack bekannt ist.$"

gBerryDescriptionPart1_Rabuta: @ 83CCEAF
	.string "Eine Seltenheit, die über und über mit$"

gBerryDescriptionPart2_Rabuta: @ 83CCED5
	.string "Haaren bewachsen ist. Sehr bitter!$"

gBerryDescriptionPart1_Nomel: @ 83CCEEF
	.string "Sehr sauer. Ein Biss betäubt die$"

gBerryDescriptionPart2_Nomel: @ 83CCF12
	.string "Geschmacksnerven für 3 Tage!$"

gBerryDescriptionPart1_Spelon: @ 83CCF36
	.string "Die leuchtend rote BEERE ist sehr$"

gBerryDescriptionPart2_Spelon: @ 83CCF5B
	.string "scharf. Gibt scharfe Substanzen ab!$"

gBerryDescriptionPart1_Pamtre: @ 83CCF80
	.string "Wird vom Meer angespült. Sie wächst$"

gBerryDescriptionPart2_Pamtre: @ 83CCFA2
	.string "an einem anderen Ort.$"

gBerryDescriptionPart1_Watmel: @ 83CCFC3
	.string "Eine große BEERE, 25 cm groß.$"

gBerryDescriptionPart2_Watmel: @ 83CCFE3
	.string "Außergewöhnlich süß.$"

gBerryDescriptionPart1_Durin: @ 83CD009
	.string "Bitter schon ihr Anblick! Sie ist so$"

gBerryDescriptionPart2_Durin: @ 83CD02A
	.string "bitter, dass niemand sie pur isst.$"

gBerryDescriptionPart1_Belue: @ 83CD052
	.string "Sie glänzt, sieht zart aus, ist extrem$"

gBerryDescriptionPart2_Belue: @ 83CD078
	.string "sauer und braucht Zeit zum Wachsen.$"

gBerryDescriptionPart1_Liechi: @ 83CD0A0
	.string "Eine geheimnisvolle BEERE. Man sagt,$"

gBerryDescriptionPart2_Liechi: @ 83CD0C5
	.string "sie enthalte die Kraft des Meeres.$"

gBerryDescriptionPart1_Ganlon: @ 83CD0E3
	.string "Eine geheimnisvolle BEERE. Man sagt,$"

gBerryDescriptionPart2_Ganlon: @ 83CD108
	.string "sie enthalte die Kraft des Landes.$"

gBerryDescriptionPart1_Salac: @ 83CD127
	.string "Eine geheimnisvolle BEERE. Man sagt,$"

gBerryDescriptionPart2_Salac: @ 83CD14C
	.string "sie enthalte die Kraft des Himmels.$"

gBerryDescriptionPart1_Petaya: @ 83CD16A
	.string "Eine geheimnisvolle BEERE. Man sagt,$"

gBerryDescriptionPart2_Petaya: @ 83CD18F
	.string "sie enthalte die Kraft allen Lebens.$"

gBerryDescriptionPart1_Apicot: @ 83CD1B7
	.string "Eine rätselhafte BEERE. Man kann$"

gBerryDescriptionPart2_Apicot: @ 83CD1DB
	.string "nicht sagen, wie und was sie ist.$"

gBerryDescriptionPart1_Lansat: @ 83CD202
	.string "Eine legendäre BEERE. Sie zu$"

gBerryDescriptionPart2_Lansat: @ 83CD220
	.string "tragen bringt Freude.$"

gBerryDescriptionPart1_Starf: @ 83CD242
	.string "So stark, dass sie an den Rand der$"

gBerryDescriptionPart2_Starf: @ 83CD265
	.string "Welt verbannt wurde. Ein Märchen?$"

gBerryDescriptionPart1_Enigma: @ 83CD288
	.string "Eine enigmatische BEERE. Sie scheint$"

gBerryDescriptionPart2_Enigma: @ 83CD2A6
	.string "die Macht der Sterne zu besitzen.$"
