@ 0x821F3B8
    .incbin "../pokeruby-other/pokeruby-de-debug.gba", 0x21F3B8, 620

@ 0x821F624
	.string "ーーーーーーーーーーーー$"

@ 0x821F631
	.string "ジュンイチ$"

@ 0x821F637
	.string "ダイゴロウ$"

@ 0x821F63D
	.string "バレンシア$"

@ 0x821F643
	.string "ハルコマチ$"

@ 0x821F649
	.string "てつじ$"

@ 0x821F64D
	.string "　　オン$"

@ 0x821F652
	.string "オフ$"

@ 0x821F655
	.string "モノラル$"

@ 0x821F65A
	.string "ステレオ$"

@ 0x821F65F
	.string "テストです$"

@ 0x821F665
	.string "うけとったって$"

@ 0x821F66D
	.string "せつぞくエラー$"

.incbin "../pokeruby-other/pokeruby-de-debug.gba", 0x21F675, 323

@ 0x821F7B8
	.string "たかさ　$"

@ 0x821F7BD
	.string "{PALETTE 1}{COLOR_HIGHLIGHT_SHADOW BLUE YELLOW MAGENTA}たかさ　　　ひこう\n"
	.string "ポケモン　　ファイル$"

@ 0x821F7DA
	.string "{PALETTE 1}{COLOR_HIGHLIGHT_SHADOW BLUE YELLOW MAGENTA}ロード\n"
	.string "セーブ$"

@ 0x821F7EA
	.string "ロードしますか？$"

@ 0x821F7F3
gUnknown_Debug_821F7F3::
	.string "セーブしますか？$"
