__attribute__((naked))
void debug_sub_810C910()
{
    asm(
        "	push	{r4, lr}\n"
        "	lsl	r0, r0, #0x18\n"
        "	lsr	r4, r0, #0x18\n"
        "	ldr	r0, ._4\n"
        "	ldrb	r1, [r0, #0x7]\n"
        "	mov	r0, #0x80\n"
        "	and	r0, r0, r1\n"
        "	cmp	r0, #0\n"
        "	bne	._3	@cond_branch\n"
        "	ldr	r1, ._4 + 4\n"
        "	mov	r0, #0x1\n"
        "	strb	r0, [r1]\n"
        "	bl	MenuZeroFillScreen\n"
        "	add	r0, r4, #0\n"
        "	bl	DestroyTask\n"
        "	ldr	r2, ._4 + 8\n"
        "	ldr	r0, ._4 + 12\n"
        "	ldrh	r1, [r0]\n"
        "	lsl	r0, r1, #0x3\n"
        "	add	r0, r0, r1\n"
        "	lsl	r1, r0, #0x2\n"
        "	add	r0, r1, r2\n"
        "	ldr	r3, ._4 + 16\n"
        "	add	r0, r0, r3\n"
        "	ldrh	r0, [r0]\n"
        "	cmp	r0, #0\n"
        "	bne	._2	@cond_branch\n"
        "	sub	r3, r3, #0x20\n"
        "	add	r0, r2, r3\n"
        "	add	r0, r1, r0\n"
        "	ldr	r1, ._4 + 20\n"
        "	mov	r2, #0x0\n"
        "	bl	HandleReadMail\n"
        "	b	._3\n"
        "._5:\n"
        "	.align	2, 0\n"
        "._4:\n"
        "	.word	gPaletteFade\n"
        "	.word	gUnknown_03000748+0x4\n"
        "	.word	gSaveBlock1\n"
        "	.word	gSpecialVar_0x8005\n"
        "	.word	0x2b6c\n"
        "	.word	debug_sub_810D388+1\n"
        "._2:\n"
        "	ldr	r3, ._6\n"
        "	add	r0, r2, r3\n"
        "	add	r0, r1, r0\n"
        "	ldr	r1, ._6 + 4\n"
        "	mov	r2, #0x1\n"
        "	bl	HandleReadMail\n"
        "._3:\n"
        "	pop	{r4}\n"
        "	pop	{r0}\n"
        "	bx	r0\n"
        "._7:\n"
        "	.align	2, 0\n"
        "._6:\n"
        "	.word	0x2b4c\n"
        "	.word	debug_sub_810D388+1\n"
        "\n"
    );
}

__attribute__((naked))
void debug_sub_810C990()
{
    asm(
        "	push	{r4, r5, lr}\n"
        "	add	sp, sp, #0xfffffffc\n"
        "	lsl	r0, r0, #0x18\n"
        "	lsr	r4, r0, #0x18\n"
        "	add	r5, r4, #0\n"
        "	ldr	r0, ._10\n"
        "	ldrh	r1, [r0, #0x2e]\n"
        "	mov	r0, #0xa0\n"
        "	and	r0, r0, r1\n"
        "	cmp	r0, #0\n"
        "	beq	._8	@cond_branch\n"
        "	ldr	r4, ._10 + 4\n"
        "	ldrh	r0, [r4]\n"
        "	add	r0, r0, #0xb\n"
        "	b	._9\n"
        "._11:\n"
        "	.align	2, 0\n"
        "._10:\n"
        "	.word	gMain\n"
        "	.word	gSpecialVar_0x8006\n"
        "._8:\n"
        "	mov	r2, #0x50\n"
        "	and	r2, r2, r1\n"
        "	cmp	r2, #0\n"
        "	beq	._12	@cond_branch\n"
        "	ldr	r4, ._14\n"
        "	ldrh	r0, [r4]\n"
        "	add	r0, r0, #0x1\n"
        "._9:\n"
        "	mov	r1, #0xc\n"
        "	bl	gScriptFuncs_End+0x3e40\n"
        "	strh	r0, [r4]\n"
        "	mov	r0, #0x1\n"
        "	mov	r1, #0x1\n"
        "	mov	r2, #0xa\n"
        "	mov	r3, #0x4\n"
        "	bl	MenuDrawTextWindow\n"
        "	ldr	r1, ._14 + 4\n"
        "	ldrh	r0, [r4]\n"
        "	lsl	r0, r0, #0x2\n"
        "	add	r0, r0, r1\n"
        "	ldr	r0, [r0]\n"
        "	mov	r1, #0x2\n"
        "	mov	r2, #0x2\n"
        "	bl	MenuPrint\n"
        "	b	._20\n"
        "._15:\n"
        "	.align	2, 0\n"
        "._14:\n"
        "	.word	gSpecialVar_0x8006\n"
        "	.word	gUnknown_083E57A4+0xe4\n"
        "._12:\n"
        "	mov	r0, #0x1\n"
        "	and	r0, r0, r1\n"
        "	cmp	r0, #0\n"
        "	beq	._16	@cond_branch\n"
        "	mov	r0, #0x1\n"
        "	neg	r0, r0\n"
        "	str	r2, [sp]\n"
        "	mov	r1, #0x0\n"
        "	mov	r2, #0x0\n"
        "	mov	r3, #0x10\n"
        "	bl	BeginNormalPaletteFade\n"
        "	ldr	r1, ._18\n"
        "	lsl	r0, r4, #0x2\n"
        "	add	r0, r0, r4\n"
        "	lsl	r0, r0, #0x3\n"
        "	add	r0, r0, r1\n"
        "	ldr	r1, ._18 + 4\n"
        "	b	._17\n"
        "._19:\n"
        "	.align	2, 0\n"
        "._18:\n"
        "	.word	gTasks\n"
        "	.word	debug_sub_810C910+1\n"
        "._16:\n"
        "	mov	r0, #0x2\n"
        "	and	r0, r0, r1\n"
        "	cmp	r0, #0\n"
        "	beq	._20	@cond_branch\n"
        "	bl	MenuDisplayMessageBox\n"
        "	ldr	r0, ._21\n"
        "	mov	r1, #0x4\n"
        "	mov	r2, #0xf\n"
        "	bl	MenuPrint\n"
        "	ldr	r1, ._21 + 4\n"
        "	ldr	r0, ._21 + 8\n"
        "	ldrh	r0, [r0]\n"
        "	lsl	r0, r0, #0x2\n"
        "	add	r0, r0, r1\n"
        "	ldr	r0, [r0]\n"
        "	mov	r1, #0x2\n"
        "	mov	r2, #0x2\n"
        "	bl	MenuPrint\n"
        "	ldr	r1, ._21 + 12\n"
        "	lsl	r0, r5, #0x2\n"
        "	add	r0, r0, r5\n"
        "	lsl	r0, r0, #0x3\n"
        "	add	r0, r0, r1\n"
        "	ldr	r1, ._21 + 16\n"
        "._17:\n"
        "	str	r1, [r0]\n"
        "._20:\n"
        "	add	sp, sp, #0x4\n"
        "	pop	{r4, r5}\n"
        "	pop	{r0}\n"
        "	bx	r0\n"
        "._22:\n"
        "	.align	2, 0\n"
        "._21:\n"
        "	.word	gUnknown_083E57A4+0x60\n"
        "	.word	gUnknown_083E57A4+0x80\n"
        "	.word	gSpecialVar_0x8004\n"
        "	.word	gTasks\n"
        "	.word	debug_sub_810CA7C+1\n"
        "\n"
    );
}

__attribute__((naked))
void debug_sub_810CA7C()
{
    asm(
        "	push	{r4, lr}\n"
        "	lsl	r0, r0, #0x18\n"
        "	lsr	r4, r0, #0x18\n"
        "	ldr	r3, ._25\n"
        "	ldrh	r1, [r3, #0x2e]\n"
        "	mov	r2, #0xf0\n"
        "	and	r2, r2, r1\n"
        "	cmp	r2, #0\n"
        "	beq	._23	@cond_branch\n"
        "	ldr	r2, ._25 + 4\n"
        "	ldrh	r0, [r2]\n"
        "	mov	r1, #0x1\n"
        "	eor	r0, r0, r1\n"
        "	strh	r0, [r2]\n"
        "	ldr	r1, ._25 + 8\n"
        "	ldrh	r0, [r2]\n"
        "	b	._24\n"
        "._26:\n"
        "	.align	2, 0\n"
        "._25:\n"
        "	.word	gMain\n"
        "	.word	gSpecialVar_0x8004\n"
        "	.word	gUnknown_083E57A4+0x80\n"
        "._23:\n"
        "	mov	r0, #0x1\n"
        "	and	r0, r0, r1\n"
        "	cmp	r0, #0\n"
        "	beq	._29	@cond_branch\n"
        "	ldrh	r0, [r3, #0x34]\n"
        "	cmp	r0, #0\n"
        "	beq	._28	@cond_branch\n"
        "	strh	r2, [r3, #0x34]\n"
        "	bl	MenuDisplayMessageBox\n"
        "	ldr	r0, ._30\n"
        "	mov	r1, #0x4\n"
        "	mov	r2, #0xf\n"
        "	bl	MenuPrint\n"
        "	mov	r0, #0x1\n"
        "	mov	r1, #0x1\n"
        "	mov	r2, #0xa\n"
        "	mov	r3, #0x4\n"
        "	bl	MenuDrawTextWindow\n"
        "	ldr	r1, ._30 + 4\n"
        "	ldr	r0, ._30 + 8\n"
        "	ldrh	r0, [r0]\n"
        "._24:\n"
        "	lsl	r0, r0, #0x2\n"
        "	add	r0, r0, r1\n"
        "	ldr	r0, [r0]\n"
        "	mov	r1, #0x2\n"
        "	mov	r2, #0x2\n"
        "	bl	MenuPrint\n"
        "	b	._29\n"
        "._31:\n"
        "	.align	2, 0\n"
        "._30:\n"
        "	.word	gUnknown_083E57A4+0x60\n"
        "	.word	gUnknown_083E57A4+0x80\n"
        "	.word	gSpecialVar_0x8004\n"
        "._28:\n"
        "	bl	MenuDisplayMessageBox\n"
        "	ldr	r0, ._32\n"
        "	mov	r1, #0x4\n"
        "	mov	r2, #0xf\n"
        "	bl	MenuPrint\n"
        "	mov	r0, #0x1\n"
        "	mov	r1, #0x1\n"
        "	mov	r2, #0xa\n"
        "	mov	r3, #0x4\n"
        "	bl	MenuDrawTextWindow\n"
        "	ldr	r1, ._32 + 4\n"
        "	ldr	r0, ._32 + 8\n"
        "	ldrh	r0, [r0]\n"
        "	lsl	r0, r0, #0x2\n"
        "	add	r0, r0, r1\n"
        "	ldr	r0, [r0]\n"
        "	mov	r1, #0x2\n"
        "	mov	r2, #0x2\n"
        "	bl	MenuPrint\n"
        "	ldr	r1, ._32 + 12\n"
        "	lsl	r0, r4, #0x2\n"
        "	add	r0, r0, r4\n"
        "	lsl	r0, r0, #0x3\n"
        "	add	r0, r0, r1\n"
        "	ldr	r1, ._32 + 16\n"
        "	str	r1, [r0]\n"
        "._29:\n"
        "	pop	{r4}\n"
        "	pop	{r0}\n"
        "	bx	r0\n"
        "._33:\n"
        "	.align	2, 0\n"
        "._32:\n"
        "	.word	gUnknown_083E57A4+0x88\n"
        "	.word	gUnknown_083E57A4+0xe4\n"
        "	.word	gSpecialVar_0x8006\n"
        "	.word	gTasks\n"
        "	.word	debug_sub_810C990+1\n"
        "\n"
    );
}

__attribute__((naked))
void debug_sub_810CB50()
{
    asm(
        "	push	{r4, r5, r6, r7, lr}\n"
        "	add	sp, sp, #0xffffffec\n"
        "	lsl	r0, r0, #0x18\n"
        "	lsr	r6, r0, #0x18\n"
        "	ldr	r1, ._36\n"
        "	mov	r0, sp\n"
        "	mov	r2, #0x6\n"
        "	bl	gScriptFuncs_End+0x5bc4\n"
        "	add	r7, sp, #0x8\n"
        "	ldr	r1, ._36 + 4\n"
        "	add	r0, r7, #0\n"
        "	mov	r2, #0x9\n"
        "	bl	gScriptFuncs_End+0x5bc4\n"
        "	mov	r2, #0x0\n"
        "	ldr	r0, ._36 + 8\n"
        "	ldrh	r1, [r0, #0x2e]\n"
        "	mov	r0, #0x1\n"
        "	and	r0, r0, r1\n"
        "	cmp	r0, #0\n"
        "	beq	._34	@cond_branch\n"
        "	ldr	r0, ._36 + 12\n"
        "	ldr	r5, ._36 + 16\n"
        "	ldrh	r1, [r5]\n"
        "	mov	r2, #0x2\n"
        "	mov	r3, #0x1\n"
        "	bl	ConvertIntToDecimalStringN\n"
        "	ldr	r0, ._36 + 20\n"
        "	ldr	r1, ._36 + 24\n"
        "	lsl	r4, r6, #0x2\n"
        "	add	r4, r4, r6\n"
        "	lsl	r4, r4, #0x3\n"
        "	add	r4, r4, r1\n"
        "	mov	r1, #0x8\n"
        "	ldsh	r2, [r4, r1]\n"
        "	mov	r1, #0xb\n"
        "	mul	r1, r1, r2\n"
        "	ldr	r2, ._36 + 28\n"
        "	add	r1, r1, r2\n"
        "	bl	StringCopy\n"
        "	ldr	r2, ._36 + 32\n"
        "	ldrh	r1, [r5]\n"
        "	lsl	r0, r1, #0x3\n"
        "	add	r0, r0, r1\n"
        "	lsl	r0, r0, #0x2\n"
        "	add	r0, r0, r2\n"
        "	ldrh	r1, [r4, #0x8]\n"
        "	ldr	r2, ._36 + 36\n"
        "	add	r0, r0, r2\n"
        "	strh	r1, [r0]\n"
        "	ldr	r4, ._36 + 40\n"
        "	add	r0, r4, #0\n"
        "	add	r1, r7, #0\n"
        "	bl	StringExpandPlaceholders\n"
        "	bl	MenuDisplayMessageBox\n"
        "	add	r0, r4, #0\n"
        "	mov	r1, #0x4\n"
        "	mov	r2, #0xf\n"
        "	bl	MenuPrint\n"
        "	add	r0, r6, #0\n"
        "	bl	DestroyTask\n"
        "	b	._35\n"
        "._37:\n"
        "	.align	2, 0\n"
        "._36:\n"
        "	.word	gUnknown_083E57A4+0x134\n"
        "	.word	gUnknown_083E57A4+0x13a\n"
        "	.word	gMain\n"
        "	.word	gStringVar1\n"
        "	.word	gSpecialVar_0x8005\n"
        "	.word	gStringVar2\n"
        "	.word	gTasks\n"
        "	.word	gSpeciesNames\n"
        "	.word	gSaveBlock1\n"
        "	.word	0x2b6a\n"
        "	.word	gStringVar4\n"
        "._34:\n"
        "	mov	r0, #0x2\n"
        "	and	r0, r0, r1\n"
        "	cmp	r0, #0\n"
        "	beq	._38	@cond_branch\n"
        "	add	r0, r6, #0\n"
        "	bl	DestroyTask\n"
        "	bl	MenuZeroFillScreen\n"
        "._35:\n"
        "	ldr	r0, ._40\n"
        "	mov	r1, #0x0\n"
        "	bl	CreateTask\n"
        "	bl	debug_sub_810D340\n"
        "	b	._47\n"
        "._41:\n"
        "	.align	2, 0\n"
        "._40:\n"
        "	.word	debug_sub_810CE1C+1\n"
        "._38:\n"
        "	mov	r0, #0xa0\n"
        "	and	r0, r0, r1\n"
        "	cmp	r0, #0\n"
        "	beq	._42	@cond_branch\n"
        "	ldr	r0, ._44\n"
        "	lsl	r4, r6, #0x2\n"
        "	add	r4, r4, r6\n"
        "	lsl	r4, r4, #0x3\n"
        "	add	r4, r4, r0\n"
        "	mov	r1, #0x8\n"
        "	ldsh	r0, [r4, r1]\n"
        "	ldr	r2, ._44 + 4\n"
        "	add	r0, r0, r2\n"
        "	mov	r1, #0xce\n"
        "	lsl	r1, r1, #0x1\n"
        "	bl	gScriptFuncs_End+0x3e40\n"
        "	strh	r0, [r4, #0x8]\n"
        "	b	._43\n"
        "._45:\n"
        "	.align	2, 0\n"
        "._44:\n"
        "	.word	gTasks\n"
        "	.word	0x19b\n"
        "._42:\n"
        "	mov	r0, #0x50\n"
        "	and	r0, r0, r1\n"
        "	cmp	r0, #0\n"
        "	beq	._46	@cond_branch\n"
        "	ldr	r0, ._48\n"
        "	lsl	r4, r6, #0x2\n"
        "	add	r4, r4, r6\n"
        "	lsl	r4, r4, #0x3\n"
        "	add	r4, r4, r0\n"
        "	mov	r1, #0x8\n"
        "	ldsh	r0, [r4, r1]\n"
        "	add	r0, r0, #0x1\n"
        "	mov	r1, #0xce\n"
        "	lsl	r1, r1, #0x1\n"
        "	bl	gScriptFuncs_End+0x3e40\n"
        "	strh	r0, [r4, #0x8]\n"
        "	mov	r2, #0x1\n"
        "._46:\n"
        "	cmp	r2, #0\n"
        "	beq	._47	@cond_branch\n"
        "._43:\n"
        "	ldr	r0, ._48 + 4\n"
        "	ldr	r1, ._48\n"
        "	lsl	r4, r6, #0x2\n"
        "	add	r4, r4, r6\n"
        "	lsl	r4, r4, #0x3\n"
        "	add	r4, r4, r1\n"
        "	mov	r2, #0x8\n"
        "	ldsh	r1, [r4, r2]\n"
        "	mov	r2, #0x2\n"
        "	mov	r3, #0x3\n"
        "	bl	ConvertIntToDecimalStringN\n"
        "	ldr	r0, ._48 + 8\n"
        "	mov	r1, #0x8\n"
        "	ldsh	r2, [r4, r1]\n"
        "	mov	r1, #0xb\n"
        "	mul	r1, r1, r2\n"
        "	ldr	r2, ._48 + 12\n"
        "	add	r1, r1, r2\n"
        "	bl	StringCopy\n"
        "	ldr	r4, ._48 + 16\n"
        "	add	r0, r4, #0\n"
        "	mov	r1, sp\n"
        "	bl	StringExpandPlaceholders\n"
        "	mov	r0, #0x0\n"
        "	mov	r1, #0x0\n"
        "	mov	r2, #0xc\n"
        "	mov	r3, #0x3\n"
        "	bl	MenuDrawTextWindow\n"
        "	add	r0, r4, #0\n"
        "	mov	r1, #0x1\n"
        "	mov	r2, #0x1\n"
        "	bl	MenuPrint\n"
        "._47:\n"
        "	add	sp, sp, #0x14\n"
        "	pop	{r4, r5, r6, r7}\n"
        "	pop	{r0}\n"
        "	bx	r0\n"
        "._49:\n"
        "	.align	2, 0\n"
        "._48:\n"
        "	.word	gTasks\n"
        "	.word	gStringVar1\n"
        "	.word	gStringVar2\n"
        "	.word	gSpeciesNames\n"
        "	.word	gStringVar4\n"
        "\n"
    );
}

__attribute__((naked))
void debug_sub_810CCEC()
{
    asm(
        "	push	{r4, r5, r6, lr}\n"
        "	mov	r6, r8\n"
        "	push	{r6}\n"
        "	add	sp, sp, #0xffffffe4\n"
        "	add	r5, r0, #0\n"
        "	lsl	r5, r5, #0x18\n"
        "	lsr	r5, r5, #0x18\n"
        "	ldr	r1, ._50\n"
        "	mov	r0, sp\n"
        "	mov	r2, #0x11\n"
        "	bl	gScriptFuncs_End+0x5bc4\n"
        "	add	r6, sp, #0x14\n"
        "	ldr	r1, ._50 + 4\n"
        "	add	r0, r6, #0\n"
        "	mov	r2, #0x7\n"
        "	bl	gScriptFuncs_End+0x5bc4\n"
        "	ldr	r0, ._50 + 8\n"
        "	mov	r8, r0\n"
        "	ldr	r0, ._50 + 12\n"
        "	ldrh	r1, [r0]\n"
        "	mov	r0, r8\n"
        "	mov	r2, #0x1\n"
        "	mov	r3, #0x1\n"
        "	bl	ConvertIntToDecimalStringN\n"
        "	ldr	r4, ._50 + 16\n"
        "	add	r0, r4, #0\n"
        "	mov	r1, sp\n"
        "	bl	StringExpandPlaceholders\n"
        "	bl	MenuDisplayMessageBox\n"
        "	add	r0, r4, #0\n"
        "	mov	r1, #0x4\n"
        "	mov	r2, #0xf\n"
        "	bl	MenuPrint\n"
        "	ldr	r1, ._50 + 20\n"
        "	mov	r0, r8\n"
        "	bl	StringCopy\n"
        "	add	r0, r4, #0\n"
        "	add	r1, r6, #0\n"
        "	bl	StringExpandPlaceholders\n"
        "	mov	r0, #0x0\n"
        "	mov	r1, #0x0\n"
        "	mov	r2, #0xc\n"
        "	mov	r3, #0x3\n"
        "	bl	MenuDrawTextWindow\n"
        "	add	r0, r6, #0\n"
        "	mov	r1, #0x1\n"
        "	mov	r2, #0x1\n"
        "	bl	MenuPrint\n"
        "	ldr	r1, ._50 + 24\n"
        "	lsl	r0, r5, #0x2\n"
        "	add	r0, r0, r5\n"
        "	lsl	r0, r0, #0x3\n"
        "	add	r0, r0, r1\n"
        "	ldr	r1, ._50 + 28\n"
        "	str	r1, [r0]\n"
        "	add	sp, sp, #0x1c\n"
        "	pop	{r3}\n"
        "	mov	r8, r3\n"
        "	pop	{r4, r5, r6}\n"
        "	pop	{r0}\n"
        "	bx	r0\n"
        "._51:\n"
        "	.align	2, 0\n"
        "._50:\n"
        "	.word	gUnknown_083E57A4+0x143\n"
        "	.word	gUnknown_083E57A4+0x154\n"
        "	.word	gStringVar1\n"
        "	.word	gSpecialVar_0x8005\n"
        "	.word	gStringVar4\n"
        "	.word	gSpeciesNames\n"
        "	.word	gTasks\n"
        "	.word	debug_sub_810CB50+1\n"
        "\n"
    );
}

__attribute__((naked))
void debug_sub_810CD9C()
{
    asm(
        "	push	{lr}\n"
        "	bl	CloseMenu\n"
        "	bl	ScriptContext1_Stop\n"
        "	bl	ScriptContext2_Enable\n"
        "	ldr	r1, ._52\n"
        "	mov	r0, #0x0\n"
        "	strb	r0, [r1]\n"
        "	ldr	r3, ._52 + 4\n"
        "	ldr	r2, ._52 + 8\n"
        "	ldr	r1, ._52 + 12\n"
        "	mov	r0, #0x0\n"
        "	strh	r0, [r1]\n"
        "	strh	r0, [r2]\n"
        "	strh	r0, [r3]\n"
        "	ldr	r0, ._52 + 16\n"
        "	bl	SetMainCallback2\n"
        "	mov	r0, #0x1\n"
        "	pop	{r1}\n"
        "	bx	r1\n"
        "._53:\n"
        "	.align	2, 0\n"
        "._52:\n"
        "	.word	gUnknown_03000748+0x4\n"
        "	.word	gSpecialVar_0x8004\n"
        "	.word	gSpecialVar_0x8005\n"
        "	.word	gSpecialVar_0x8006\n"
        "	.word	debug_sub_810D388+1\n"
        "\n"
    );
}

__attribute__((naked))
void debug_sub_810CDE0()
{
    asm(
        "	push	{lr}\n"
        "	bl	UpdatePaletteFade\n"
        "	bl	RunTasks\n"
        "	pop	{r0}\n"
        "	bx	r0\n"
        "\n"
    );
}

__attribute__((naked))
void debug_sub_810CDF0()
{
    asm(
        "	push	{lr}\n"
        "	ldr	r1, ._54\n"
        "	mov	r0, #0x0\n"
        "	strh	r0, [r1, #0x34]\n"
        "	strh	r0, [r1, #0x36]\n"
        "	ldr	r1, ._54 + 4\n"
        "	ldr	r0, ._54 + 8\n"
        "	str	r0, [r1]\n"
        "	ldr	r0, ._54 + 12\n"
        "	bl	SetMainCallback2\n"
        "	pop	{r0}\n"
        "	bx	r0\n"
        "._55:\n"
        "	.align	2, 0\n"
        "._54:\n"
        "	.word	gMain\n"
        "	.word	gFieldCallback\n"
        "	.word	mapldr_default+1\n"
        "	.word	c2_exit_to_overworld_2_switch+1\n"
        "\n"
    );
}

__attribute__((naked))
void debug_sub_810CE1C()
{
    asm(
        "	push	{r4, lr}\n"
        "	lsl	r0, r0, #0x18\n"
        "	lsr	r4, r0, #0x18\n"
        "	ldr	r0, ._57\n"
        "	ldr	r0, [r0]\n"
        "	bl	gScriptFuncs_End+0x3cf4\n"
        "	lsl	r0, r0, #0x18\n"
        "	lsr	r0, r0, #0x18\n"
        "	cmp	r0, #0x1\n"
        "	bne	._56	@cond_branch\n"
        "	bl	CloseMenu\n"
        "	add	r0, r4, #0\n"
        "	bl	DestroyTask\n"
        "._56:\n"
        "	pop	{r4}\n"
        "	pop	{r0}\n"
        "	bx	r0\n"
        "._58:\n"
        "	.align	2, 0\n"
        "._57:\n"
        "	.word	gCallback_03004AE8\n"
        "\n"
    );
}

__attribute__((naked))
void debug_sub_810CE48()
{
    asm(
        "	push	{r4, lr}\n"
        "	bl	ProcessMenuInput\n"
        "	lsl	r0, r0, #0x18\n"
        "	asr	r1, r0, #0x18\n"
        "	mov	r0, #0x2\n"
        "	neg	r0, r0\n"
        "	cmp	r1, r0\n"
        "	beq	._59	@cond_branch\n"
        "	add	r0, r0, #0x1\n"
        "	cmp	r1, r0\n"
        "	bne	._60	@cond_branch\n"
        "	bl	MenuZeroFillScreen\n"
        "	bl	debug_sub_810D340\n"
        "._59:\n"
        "	mov	r0, #0x0\n"
        "	b	._61\n"
        "._60:\n"
        "	ldr	r0, ._62\n"
        "	strh	r1, [r0]\n"
        "	ldr	r4, ._62 + 4\n"
        "	ldrh	r0, [r4]\n"
        "	mov	r1, #0xc\n"
        "	bl	gScriptFuncs_End+0x43d0\n"
        "	strh	r0, [r4]\n"
        "	ldr	r0, ._62 + 8\n"
        "	mov	r1, #0x0\n"
        "	bl	CreateTask\n"
        "	ldr	r1, ._62 + 12\n"
        "	mov	r2, #0x0\n"
        "	mov	r0, #0x1\n"
        "	strh	r0, [r1, #0x34]\n"
        "	strh	r2, [r1, #0x36]\n"
        "._61:\n"
        "	pop	{r4}\n"
        "	pop	{r1}\n"
        "	bx	r1\n"
        "._63:\n"
        "	.align	2, 0\n"
        "._62:\n"
        "	.word	gSpecialVar_0x8005\n"
        "	.word	gSpecialVar_0x8006\n"
        "	.word	debug_sub_810CA7C+1\n"
        "	.word	gMain\n"
        "\n"
    );
}

__attribute__((naked))
void debug_sub_810CEA4()
{
    asm(
        "	push	{lr}\n"
        "	ldr	r0, ._66\n"
        "	ldrb	r1, [r0, #0x7]\n"
        "	mov	r0, #0x80\n"
        "	and	r0, r0, r1\n"
        "	cmp	r0, #0\n"
        "	beq	._64	@cond_branch\n"
        "	mov	r0, #0x0\n"
        "	b	._65\n"
        "._67:\n"
        "	.align	2, 0\n"
        "._66:\n"
        "	.word	gPaletteFade\n"
        "._64:\n"
        "	ldr	r1, ._68\n"
        "	mov	r0, #0x4\n"
        "	strh	r0, [r1]\n"
        "	bl	sub_80E60D8\n"
        "	mov	r0, #0x1\n"
        "._65:\n"
        "	pop	{r1}\n"
        "	bx	r1\n"
        "._69:\n"
        "	.align	2, 0\n"
        "._68:\n"
        "	.word	gSpecialVar_0x8004\n"
        "\n"
    );
}

__attribute__((naked))
void debug_sub_810CED0()
{
    asm(
        "	push	{r4, r5, r6, lr}\n"
        "	add	sp, sp, #0xffffffdc\n"
        "	ldr	r1, ._73\n"
        "	mov	r0, sp\n"
        "	mov	r2, #0x23\n"
        "	bl	gScriptFuncs_End+0x5bc4\n"
        "	bl	ProcessMenuInput\n"
        "	lsl	r0, r0, #0x18\n"
        "	asr	r1, r0, #0x18\n"
        "	mov	r0, #0x2\n"
        "	neg	r0, r0\n"
        "	cmp	r1, r0\n"
        "	beq	._76	@cond_branch\n"
        "	add	r0, r0, #0x1\n"
        "	cmp	r1, r0\n"
        "	bne	._71	@cond_branch\n"
        "	bl	MenuZeroFillScreen\n"
        "	b	._72\n"
        "._74:\n"
        "	.align	2, 0\n"
        "._73:\n"
        "	.word	gUnknown_083E57A4+0x15b\n"
        "._71:\n"
        "	ldr	r5, ._77\n"
        "	strh	r1, [r5]\n"
        "	ldr	r6, ._77 + 4\n"
        "	lsl	r0, r1, #0x3\n"
        "	add	r0, r0, r1\n"
        "	lsl	r0, r0, #0x2\n"
        "	add	r0, r0, r6\n"
        "	ldr	r1, ._77 + 8\n"
        "	add	r0, r0, r1\n"
        "	ldrh	r0, [r0]\n"
        "	sub	r0, r0, #0x79\n"
        "	lsl	r0, r0, #0x10\n"
        "	lsr	r0, r0, #0x10\n"
        "	cmp	r0, #0xb\n"
        "	bls	._75	@cond_branch\n"
        "	ldrh	r1, [r5]\n"
        "	lsl	r0, r1, #0x3\n"
        "	add	r0, r0, r1\n"
        "	lsl	r0, r0, #0x2\n"
        "	add	r0, r0, r6\n"
        "	ldr	r2, ._77 + 8\n"
        "	add	r0, r0, r2\n"
        "	ldr	r1, ._77 + 12\n"
        "	strh	r1, [r0]\n"
        "	ldrh	r1, [r5]\n"
        "	lsl	r0, r1, #0x3\n"
        "	add	r0, r0, r1\n"
        "	lsl	r0, r0, #0x2\n"
        "	sub	r2, r2, #0xe\n"
        "	add	r1, r6, r2\n"
        "	add	r0, r0, r1\n"
        "	ldr	r4, ._77 + 16\n"
        "	add	r1, r4, #0\n"
        "	bl	StringCopy\n"
        "	ldrh	r1, [r5]\n"
        "	lsl	r0, r1, #0x3\n"
        "	add	r0, r0, r1\n"
        "	lsl	r0, r0, #0x2\n"
        "	ldr	r2, ._77 + 20\n"
        "	add	r1, r6, r2\n"
        "	add	r0, r0, r1\n"
        "	add	r4, r4, #0xa\n"
        "	ldr	r1, [r4]\n"
        "	str	r1, [r0]\n"
        "	ldr	r1, ._77 + 24\n"
        "	ldr	r0, ._77 + 28\n"
        "	str	r0, [r1]\n"
        "	b	._76\n"
        "._78:\n"
        "	.align	2, 0\n"
        "._77:\n"
        "	.word	gSpecialVar_0x8005\n"
        "	.word	gSaveBlock1\n"
        "	.word	0x2b6c\n"
        "	.word	0xffff\n"
        "	.word	gSaveBlock2\n"
        "	.word	0x2b66\n"
        "	.word	gCallback_03004AE8\n"
        "	.word	debug_sub_810CEA4+1\n"
        "._75:\n"
        "	bl	MenuZeroFillScreen\n"
        "	bl	MenuDisplayMessageBox\n"
        "	mov	r0, sp\n"
        "	mov	r1, #0x4\n"
        "	mov	r2, #0xf\n"
        "	bl	MenuPrint\n"
        "._72:\n"
        "	bl	debug_sub_810D340\n"
        "._76:\n"
        "	mov	r0, #0x0\n"
        "	add	sp, sp, #0x24\n"
        "	pop	{r4, r5, r6}\n"
        "	pop	{r1}\n"
        "	bx	r1\n"
        "\n"
    );
}

__attribute__((naked))
void debug_sub_810CFA4()
{
    asm(
        "	push	{lr}\n"
        "	add	sp, sp, #0xffffffe0\n"
        "	ldr	r1, ._82\n"
        "	mov	r0, sp\n"
        "	mov	r2, #0x1f\n"
        "	bl	gScriptFuncs_End+0x5bc4\n"
        "	bl	ProcessMenuInput\n"
        "	lsl	r0, r0, #0x18\n"
        "	asr	r2, r0, #0x18\n"
        "	mov	r0, #0x2\n"
        "	neg	r0, r0\n"
        "	cmp	r2, r0\n"
        "	beq	._79	@cond_branch\n"
        "	add	r0, r0, #0x1\n"
        "	cmp	r2, r0\n"
        "	bne	._80	@cond_branch\n"
        "	bl	MenuZeroFillScreen\n"
        "	b	._81\n"
        "._83:\n"
        "	.align	2, 0\n"
        "._82:\n"
        "	.word	gUnknown_083E57A4+0x17e\n"
        "._80:\n"
        "	ldr	r0, ._86\n"
        "	strh	r2, [r0]\n"
        "	ldr	r1, ._86 + 4\n"
        "	lsl	r0, r2, #0x3\n"
        "	add	r0, r0, r2\n"
        "	lsl	r0, r0, #0x2\n"
        "	add	r0, r0, r1\n"
        "	ldr	r1, ._86 + 8\n"
        "	add	r0, r0, r1\n"
        "	ldrh	r0, [r0]\n"
        "	sub	r0, r0, #0x79\n"
        "	lsl	r0, r0, #0x10\n"
        "	lsr	r0, r0, #0x10\n"
        "	cmp	r0, #0xb\n"
        "	bls	._84	@cond_branch\n"
        "	ldr	r0, ._86 + 12\n"
        "	mov	r1, #0x0\n"
        "	bl	CreateTask\n"
        "	mov	r0, #0x1\n"
        "	b	._85\n"
        "._87:\n"
        "	.align	2, 0\n"
        "._86:\n"
        "	.word	gSpecialVar_0x8005\n"
        "	.word	gSaveBlock1\n"
        "	.word	0x2b6c\n"
        "	.word	debug_sub_810CCEC+1\n"
        "._84:\n"
        "	bl	MenuZeroFillScreen\n"
        "	bl	MenuDisplayMessageBox\n"
        "	mov	r0, sp\n"
        "	mov	r1, #0x4\n"
        "	mov	r2, #0xf\n"
        "	bl	MenuPrint\n"
        "._81:\n"
        "	bl	debug_sub_810D340\n"
        "._79:\n"
        "	mov	r0, #0x0\n"
        "._85:\n"
        "	add	sp, sp, #0x20\n"
        "	pop	{r1}\n"
        "	bx	r1\n"
        "\n"
    );
}

__attribute__((naked))
void debug_sub_810D030()
{
    asm(
        "	push	{r4, r5, r6, r7, lr}\n"
        "	add	sp, sp, #0xffffffcc\n"
        "	ldr	r1, ._91\n"
        "	mov	r0, sp\n"
        "	mov	r2, #0x10\n"
        "	bl	gScriptFuncs_End+0x5bc4\n"
        "	add	r5, sp, #0x10\n"
        "	ldr	r1, ._91 + 4\n"
        "	add	r0, r5, #0\n"
        "	mov	r2, #0x21\n"
        "	bl	gScriptFuncs_End+0x5bc4\n"
        "	bl	ProcessMenuInput\n"
        "	lsl	r0, r0, #0x18\n"
        "	asr	r1, r0, #0x18\n"
        "	mov	r0, #0x2\n"
        "	neg	r0, r0\n"
        "	cmp	r1, r0\n"
        "	beq	._88	@cond_branch\n"
        "	add	r0, r0, #0x1\n"
        "	cmp	r1, r0\n"
        "	bne	._89	@cond_branch\n"
        "	bl	MenuZeroFillScreen\n"
        "	b	._90\n"
        "._92:\n"
        "	.align	2, 0\n"
        "._91:\n"
        "	.word	gUnknown_083E57A4+0x19d\n"
        "	.word	gUnknown_083E57A4+0x1ad\n"
        "._89:\n"
        "	ldr	r2, ._96\n"
        "	strh	r1, [r2]\n"
        "	ldr	r3, ._96 + 4\n"
        "	ldrh	r1, [r2]\n"
        "	lsl	r0, r1, #0x3\n"
        "	add	r0, r0, r1\n"
        "	lsl	r0, r0, #0x2\n"
        "	add	r0, r0, r3\n"
        "	ldr	r1, ._96 + 8\n"
        "	add	r0, r0, r1\n"
        "	ldrh	r1, [r0]\n"
        "	ldr	r0, ._96 + 12\n"
        "	add	r4, r2, #0\n"
        "	cmp	r1, r0\n"
        "	beq	._94	@cond_branch\n"
        "	cmp	r1, #0\n"
        "	beq	._94	@cond_branch\n"
        "	bl	MenuZeroFillScreen\n"
        "	bl	MenuDisplayMessageBox\n"
        "	add	r0, r5, #0\n"
        "	b	._95\n"
        "._97:\n"
        "	.align	2, 0\n"
        "._96:\n"
        "	.word	gSpecialVar_0x8005\n"
        "	.word	gSaveBlock1\n"
        "	.word	0x2b6c\n"
        "	.word	0xffff\n"
        "._94:\n"
        "	ldrh	r1, [r4]\n"
        "	lsl	r0, r1, #0x3\n"
        "	add	r0, r0, r1\n"
        "	lsl	r0, r0, #0x2\n"
        "	add	r0, r0, r3\n"
        "	ldr	r5, ._99\n"
        "	add	r0, r0, r5\n"
        "	mov	r2, #0x0\n"
        "	strh	r2, [r0]\n"
        "	ldrh	r1, [r4]\n"
        "	lsl	r0, r1, #0x3\n"
        "	add	r0, r0, r1\n"
        "	lsl	r0, r0, #0x2\n"
        "	add	r0, r0, r3\n"
        "	ldr	r1, ._99 + 4\n"
        "	add	r0, r0, r1\n"
        "	strh	r2, [r0]\n"
        "	ldrh	r1, [r4]\n"
        "	lsl	r0, r1, #0x3\n"
        "	add	r0, r0, r1\n"
        "	lsl	r0, r0, #0x2\n"
        "	add	r0, r0, r3\n"
        "	sub	r5, r5, #0xe\n"
        "	add	r0, r0, r5\n"
        "	mov	r1, #0xff\n"
        "	strb	r1, [r0]\n"
        "	ldrh	r1, [r4]\n"
        "	lsl	r0, r1, #0x3\n"
        "	add	r0, r0, r1\n"
        "	lsl	r0, r0, #0x2\n"
        "	add	r5, r5, #0x8\n"
        "	add	r1, r3, r5\n"
        "	add	r0, r0, r1\n"
        "	str	r2, [r0]\n"
        "	mov	r0, #0x0\n"
        "	ldr	r1, ._99 + 8\n"
        "	mov	ip, r1\n"
        "	sub	r5, r5, #0x1a\n"
        "	add	r7, r3, r5\n"
        "	add	r6, r4, #0\n"
        "	ldr	r1, ._99 + 12\n"
        "	add	r5, r1, #0\n"
        "._98:\n"
        "	lsl	r1, r0, #0x18\n"
        "	asr	r1, r1, #0x18\n"
        "	lsl	r3, r1, #0x1\n"
        "	ldrh	r2, [r6]\n"
        "	lsl	r0, r2, #0x3\n"
        "	add	r0, r0, r2\n"
        "	lsl	r0, r0, #0x2\n"
        "	add	r3, r3, r0\n"
        "	add	r3, r3, r7\n"
        "	ldrh	r0, [r3]\n"
        "	orr	r0, r0, r5\n"
        "	strh	r0, [r3]\n"
        "	add	r1, r1, #0x1\n"
        "	lsl	r1, r1, #0x18\n"
        "	lsr	r0, r1, #0x18\n"
        "	asr	r1, r1, #0x18\n"
        "	cmp	r1, #0x8\n"
        "	ble	._98	@cond_branch\n"
        "	ldrh	r1, [r4]\n"
        "	mov	r0, ip\n"
        "	mov	r2, #0x1\n"
        "	mov	r3, #0x1\n"
        "	bl	ConvertIntToDecimalStringN\n"
        "	ldr	r4, ._99 + 16\n"
        "	add	r0, r4, #0\n"
        "	mov	r1, sp\n"
        "	bl	StringExpandPlaceholders\n"
        "	bl	MenuZeroFillScreen\n"
        "	bl	MenuDisplayMessageBox\n"
        "	add	r0, r4, #0\n"
        "._95:\n"
        "	mov	r1, #0x4\n"
        "	mov	r2, #0xf\n"
        "	bl	MenuPrint\n"
        "._90:\n"
        "	bl	debug_sub_810D340\n"
        "._88:\n"
        "	mov	r0, #0x0\n"
        "	add	sp, sp, #0x34\n"
        "	pop	{r4, r5, r6, r7}\n"
        "	pop	{r1}\n"
        "	bx	r1\n"
        "._100:\n"
        "	.align	2, 0\n"
        "._99:\n"
        "	.word	0x2b6c\n"
        "	.word	0x2b6a\n"
        "	.word	gStringVar1\n"
        "	.word	0xffff\n"
        "	.word	gStringVar4\n"
        "\n"
    );
}

__attribute__((naked))
void debug_sub_810D174()
{
    asm(
        "	push	{r4, r5, r6, r7, lr}\n"
        "	mov	r7, sl\n"
        "	mov	r6, r9\n"
        "	mov	r5, r8\n"
        "	push	{r5, r6, r7}\n"
        "	add	sp, sp, #0xfffffeec\n"
        "	lsl	r0, r0, #0x18\n"
        "	lsr	r7, r0, #0x18\n"
        "	ldr	r1, ._103\n"
        "	add	r0, sp, #0x8\n"
        "	mov	r2, #0xc\n"
        "	bl	gScriptFuncs_End+0x5bc4\n"
        "	mov	r5, #0x0\n"
        "	mov	r0, sp\n"
        "	add	r0, r0, #0x14\n"
        "	str	r0, [sp, #0x110]\n"
        "	add	r1, sp, #0xc8\n"
        "	mov	r8, r1\n"
        "	add	r2, sp, #0xcc\n"
        "	mov	sl, r2\n"
        "	ldr	r0, ._103 + 4\n"
        "	mov	r9, r0\n"
        "._109:\n"
        "	ldr	r0, ._103 + 8\n"
        "	add	r1, r5, #0\n"
        "	mov	r2, #0x1\n"
        "	mov	r3, #0x1\n"
        "	bl	ConvertIntToDecimalStringN\n"
        "	lsl	r1, r5, #0x3\n"
        "	add	r0, r1, r5\n"
        "	lsl	r0, r0, #0x2\n"
        "	add r0, r0, r9\n"
        "	ldr	r2, ._103 + 12\n"
        "	add	r4, r0, r2\n"
        "	ldrh	r0, [r4]\n"
        "	add	r6, r1, #0\n"
        "	ldr	r1, ._103 + 16\n"
        "	cmp	r0, r1\n"
        "	bne	._101	@cond_branch\n"
        "	ldr	r0, ._103 + 20\n"
        "	mov	r1, #0x1\n"
        "	b	._102\n"
        "._104:\n"
        "	.align	2, 0\n"
        "._103:\n"
        "	.word	gUnknown_083E57A4+0x1ce\n"
        "	.word	gSaveBlock1\n"
        "	.word	gStringVar1\n"
        "	.word	0x2b6c\n"
        "	.word	0xffff\n"
        "	.word	gStringVar2\n"
        "._101:\n"
        "	sub	r0, r0, #0x79\n"
        "	lsl	r0, r0, #0x10\n"
        "	lsr	r0, r0, #0x10\n"
        "	cmp	r0, #0xb\n"
        "	bhi	._105	@cond_branch\n"
        "	ldr	r0, ._107\n"
        "	mov	r1, #0x2\n"
        "._102:\n"
        "	mov	r2, #0x1\n"
        "	mov	r3, #0x1\n"
        "	bl	ConvertIntToDecimalStringN\n"
        "	b	._106\n"
        "._108:\n"
        "	.align	2, 0\n"
        "._107:\n"
        "	.word	gStringVar2\n"
        "._105:\n"
        "	ldr	r0, ._114\n"
        "	mov	r1, #0x0\n"
        "	mov	r2, #0x1\n"
        "	mov	r3, #0x1\n"
        "	bl	ConvertIntToDecimalStringN\n"
        "	mov	r0, #0x0\n"
        "	strh	r0, [r4]\n"
        "._106:\n"
        "	add	r0, r6, r5\n"
        "	lsl	r0, r0, #0x2\n"
        "	add r0, r0, r9\n"
        "	ldr	r2, ._114 + 4\n"
        "	add	r0, r0, r2\n"
        "	ldrh	r1, [r0]\n"
        "	mov	r0, #0xb\n"
        "	mul	r1, r1, r0\n"
        "	ldr	r0, ._114 + 8\n"
        "	add	r1, r1, r0\n"
        "	ldr	r0, ._114 + 12\n"
        "	bl	StringCopy\n"
        "	lsl	r4, r5, #0x2\n"
        "	add	r4, r4, r5\n"
        "	lsl	r4, r4, #0x2\n"
        "	ldr	r0, [sp, #0x110]\n"
        "	add	r4, r0, r4\n"
        "	add	r0, r4, #0\n"
        "	add	r1, sp, #0x8\n"
        "	bl	StringExpandPlaceholders\n"
        "	mov	r1, r8\n"
        "	add	r0, r1, r6\n"
        "	str	r4, [r0]\n"
        "	mov	r2, sl\n"
        "	add	r0, r2, r6\n"
        "	mov	r4, #0x0\n"
        "	str	r4, [r0]\n"
        "	add	r0, r5, #1\n"
        "	lsl	r0, r0, #0x18\n"
        "	lsr	r5, r0, #0x18\n"
        "	cmp	r5, #0x8\n"
        "	bls	._109	@cond_branch\n"
        "	mov	r0, #0x0\n"
        "	mov	r1, #0x0\n"
        "	mov	r2, #0x10\n"
        "	mov	r3, #0x13\n"
        "	bl	MenuDrawTextWindow\n"
        "	mov	r0, #0x2\n"
        "	mov	r1, #0x1\n"
        "	mov	r2, #0x9\n"
        "	mov	r3, r8\n"
        "	bl	PrintMenuItems\n"
        "	str	r4, [sp]\n"
        "	mov	r0, #0xf\n"
        "	str	r0, [sp, #0x4]\n"
        "	mov	r0, #0x0\n"
        "	mov	r1, #0x1\n"
        "	mov	r2, #0x1\n"
        "	mov	r3, #0x9\n"
        "	bl	InitMenu\n"
        "	cmp	r7, #0x1\n"
        "	beq	._110	@cond_branch\n"
        "	cmp	r7, #0x1\n"
        "	bgt	._111	@cond_branch\n"
        "	cmp	r7, #0\n"
        "	beq	._112	@cond_branch\n"
        "	b	._118\n"
        "._115:\n"
        "	.align	2, 0\n"
        "._114:\n"
        "	.word	gStringVar2\n"
        "	.word	0x2b6a\n"
        "	.word	gSpeciesNames\n"
        "	.word	gStringVar3\n"
        "._111:\n"
        "	cmp	r7, #0x2\n"
        "	beq	._116	@cond_branch\n"
        "	cmp	r7, #0x3\n"
        "	beq	._117	@cond_branch\n"
        "	b	._118\n"
        "._112:\n"
        "	ldr	r1, ._120\n"
        "	ldr	r0, ._120 + 4\n"
        "	b	._125\n"
        "._121:\n"
        "	.align	2, 0\n"
        "._120:\n"
        "	.word	gCallback_03004AE8\n"
        "	.word	debug_sub_810CE48+1\n"
        "._110:\n"
        "	ldr	r1, ._123\n"
        "	ldr	r0, ._123 + 4\n"
        "	b	._125\n"
        "._124:\n"
        "	.align	2, 0\n"
        "._123:\n"
        "	.word	gCallback_03004AE8\n"
        "	.word	debug_sub_810CED0+1\n"
        "._116:\n"
        "	ldr	r1, ._126\n"
        "	ldr	r0, ._126 + 4\n"
        "	b	._125\n"
        "._127:\n"
        "	.align	2, 0\n"
        "._126:\n"
        "	.word	gCallback_03004AE8\n"
        "	.word	debug_sub_810CFA4+1\n"
        "._117:\n"
        "	ldr	r1, ._128\n"
        "	ldr	r0, ._128 + 4\n"
        "._125:\n"
        "	str	r0, [r1]\n"
        "._118:\n"
        "	add	sp, sp, #0x114\n"
        "	pop	{r3, r4, r5}\n"
        "	mov	r8, r3\n"
        "	mov	r9, r4\n"
        "	mov	sl, r5\n"
        "	pop	{r4, r5, r6, r7}\n"
        "	pop	{r0}\n"
        "	bx	r0\n"
        "._129:\n"
        "	.align	2, 0\n"
        "._128:\n"
        "	.word	gCallback_03004AE8\n"
        "	.word	debug_sub_810D030+1\n"
        "\n"
    );
}

__attribute__((naked))
void debug_sub_810D2F4()
{
    asm(
        "	push	{lr}\n"
        "	bl	ProcessMenuInput\n"
        "	lsl	r2, r0, #0x18\n"
        "	asr	r1, r2, #0x18\n"
        "	mov	r0, #0x2\n"
        "	neg	r0, r0\n"
        "	cmp	r1, r0\n"
        "	beq	._130	@cond_branch\n"
        "	add	r0, r0, #0x1\n"
        "	cmp	r1, r0\n"
        "	bne	._131	@cond_branch\n"
        "	ldr	r0, ._133\n"
        "	bl	SetMainCallback2\n"
        "	b	._140\n"
        "._134:\n"
        "	.align	2, 0\n"
        "._133:\n"
        "	.word	debug_sub_810CDF0+1\n"
        "._131:\n"
        "	cmp	r1, #0x1\n"
        "	beq	._139	@cond_branch\n"
        "	cmp	r1, #0x1\n"
        "	bgt	._136	@cond_branch\n"
        "	cmp	r1, #0\n"
        "	beq	._139	@cond_branch\n"
        "	b	._140\n"
        "._136:\n"
        "	cmp	r1, #0x2\n"
        "	beq	._139	@cond_branch\n"
        "	cmp	r1, #0x3\n"
        "	bne	._140	@cond_branch\n"
        "._139:\n"
        "	lsr	r0, r2, #0x18\n"
        "	bl	debug_sub_810D174\n"
        "._130:\n"
        "	mov	r0, #0x0\n"
        "	b	._141\n"
        "._140:\n"
        "	mov	r0, #0x1\n"
        "._141:\n"
        "	pop	{r1}\n"
        "	bx	r1\n"
        "\n"
    );
}

__attribute__((naked))
void debug_sub_810D340()
{
    asm(
        "	push	{lr}\n"
        "	add	sp, sp, #0xfffffff8\n"
        "	mov	r0, #0x0\n"
        "	mov	r1, #0x0\n"
        "	mov	r2, #0x9\n"
        "	mov	r3, #0x9\n"
        "	bl	MenuDrawTextWindow\n"
        "	ldr	r3, ._142\n"
        "	mov	r0, #0x2\n"
        "	mov	r1, #0x1\n"
        "	mov	r2, #0x4\n"
        "	bl	PrintMenuItems\n"
        "	mov	r0, #0x0\n"
        "	str	r0, [sp]\n"
        "	mov	r0, #0x8\n"
        "	str	r0, [sp, #0x4]\n"
        "	mov	r0, #0x0\n"
        "	mov	r1, #0x1\n"
        "	mov	r2, #0x1\n"
        "	mov	r3, #0x4\n"
        "	bl	InitMenu\n"
        "	ldr	r1, ._142 + 4\n"
        "	ldr	r0, ._142 + 8\n"
        "	str	r0, [r1]\n"
        "	add	sp, sp, #0x8\n"
        "	pop	{r0}\n"
        "	bx	r0\n"
        "._143:\n"
        "	.align	2, 0\n"
        "._142:\n"
        "	.word	gUnknown_083E57A4+0x1dc\n"
        "	.word	gCallback_03004AE8\n"
        "	.word	debug_sub_810D2F4+1\n"
        "\n"
    );
}

__attribute__((naked))
void debug_sub_810D388()
{
    asm(
        "	push	{r4, lr}\n"
        "	add	sp, sp, #0xfffffff8\n"
        "	ldr	r1, ._146\n"
        "	ldr	r2, ._146 + 4\n"
        "	add	r0, r1, r2\n"
        "	ldrb	r0, [r0]\n"
        "	add	r2, r1, #0\n"
        "	cmp	r0, #0x8\n"
        "	bls	._144	@cond_branch\n"
        "	b	._181\n"
        "._144:\n"
        "	lsl	r0, r0, #0x2\n"
        "	ldr	r1, ._146 + 8\n"
        "	add	r0, r0, r1\n"
        "	ldr	r0, [r0]\n"
        "	mov	pc, r0\n"
        "._147:\n"
        "	.align	2, 0\n"
        "._146:\n"
        "	.word	gMain\n"
        "	.word	0x43c\n"
        "	.word	._148\n"
        "._148:\n"
        "	.word	._149\n"
        "	.word	._150\n"
        "	.word	._151\n"
        "	.word	._152\n"
        "	.word	._153\n"
        "	.word	._154\n"
        "	.word	._155\n"
        "	.word	._156\n"
        "	.word	._157\n"
        "._149:\n"
        "	ldr	r3, ._160\n"
        "	ldrb	r4, [r3]\n"
        "	cmp	r4, #0\n"
        "	beq	._158	@cond_branch\n"
        "	ldr	r1, ._160 + 4\n"
        "	add	r0, r2, r1\n"
        "	mov	r2, #0x0\n"
        "	mov	r1, #0x2\n"
        "	strb	r1, [r0]\n"
        "	strb	r2, [r3]\n"
        "	b	._181\n"
        "._161:\n"
        "	.align	2, 0\n"
        "._160:\n"
        "	.word	gUnknown_03000748+0x4\n"
        "	.word	0x43c\n"
        "._158:\n"
        "	bl	remove_some_task\n"
        "	bl	ResetPaletteFade\n"
        "	ldr	r0, ._163\n"
        "	bl	SetVBlankCallback\n"
        "	mov	r0, #0x1\n"
        "	neg	r0, r0\n"
        "	str	r4, [sp]\n"
        "	mov	r1, #0x0\n"
        "	mov	r2, #0x0\n"
        "	mov	r3, #0x10\n"
        "	bl	BeginNormalPaletteFade\n"
        "	b	._182\n"
        "._164:\n"
        "	.align	2, 0\n"
        "._163:\n"
        "	.word	sub_80F8F18+1\n"
        "._150:\n"
        "	bl	UpdatePaletteFade\n"
        "	lsl	r0, r0, #0x18\n"
        "	cmp	r0, #0\n"
        "	beq	._165	@cond_branch\n"
        "	b	._181\n"
        "._165:\n"
        "	b	._182\n"
        "._151:\n"
        "	mov	r0, #0x0\n"
        "	bl	SetVBlankCallback\n"
        "	ldr	r0, ._169\n"
        "	mov	r1, #0x0\n"
        "	strh	r1, [r0]\n"
        "	add	r0, r0, #0x2\n"
        "	strh	r1, [r0]\n"
        "	add	r0, r0, #0x2\n"
        "	strh	r1, [r0]\n"
        "	add	r0, r0, #0x2\n"
        "	strh	r1, [r0]\n"
        "	add	r0, r0, #0x4\n"
        "	strh	r1, [r0]\n"
        "	sub	r0, r0, #0x2\n"
        "	strh	r1, [r0]\n"
        "	add	r0, r0, #0x4\n"
        "	strh	r1, [r0]\n"
        "	add	r0, r0, #0x2\n"
        "	strh	r1, [r0]\n"
        "	b	._182\n"
        "._170:\n"
        "	.align	2, 0\n"
        "._169:\n"
        "	.word	0x4000010\n"
        "._152:\n"
        "	bl	ResetSpriteData\n"
        "	bl	ResetTasks\n"
        "	bl	FreeAllSpritePalettes\n"
        "	b	._182\n"
        "._153:\n"
        "	ldr	r4, ._173\n"
        "	add	r0, r4, #0\n"
        "	bl	SetUpWindowConfig\n"
        "	add	r0, r4, #0\n"
        "	bl	InitMenuWindow\n"
        "	bl	MenuZeroFillScreen\n"
        "	b	._182\n"
        "._174:\n"
        "	.align	2, 0\n"
        "._173:\n"
        "	.word	gWindowConfig_81E6CE4\n"
        "._154:\n"
        "	ldr	r4, ._176\n"
        "	ldr	r0, [r4]\n"
        "	mov	r1, #0x0\n"
        "	mov	r2, #0x20\n"
        "	bl	LoadPalette\n"
        "	ldr	r0, [r4, #0x4]\n"
        "	mov	r1, #0xc0\n"
        "	lsl	r1, r1, #0x13\n"
        "	bl	gScriptFuncs_End+0x3cb8\n"
        "	add	r1, sp, #0x4\n"
        "	mov	r0, #0x1\n"
        "	strh	r0, [r1]\n"
        "	ldr	r1, ._176 + 4\n"
        "	add	r2, sp, #0x4\n"
        "	str	r2, [r1]\n"
        "	ldr	r0, ._176 + 8\n"
        "	str	r0, [r1, #0x4]\n"
        "	ldr	r0, ._176 + 12\n"
        "	str	r0, [r1, #0x8]\n"
        "	ldr	r0, [r1, #0x8]\n"
        "	b	._182\n"
        "._177:\n"
        "	.align	2, 0\n"
        "._176:\n"
        "	.word	gMailGraphicsTable\n"
        "	.word	0x40000d4\n"
        "	.word	0x6004000\n"
        "	.word	0x81000280\n"
        "._155:\n"
        "	ldr	r1, ._179\n"
        "	ldr	r2, ._179 + 4\n"
        "	add	r0, r2, #0\n"
        "	strh	r0, [r1]\n"
        "	add	r1, r1, #0x2\n"
        "	ldr	r2, ._179 + 8\n"
        "	add	r0, r2, #0\n"
        "	strh	r0, [r1]\n"
        "	add	r1, r1, #0x46\n"
        "	mov	r0, #0x0\n"
        "	strh	r0, [r1]\n"
        "	sub	r1, r1, #0x50\n"
        "	mov	r2, #0xd0\n"
        "	lsl	r2, r2, #0x2\n"
        "	add	r0, r2, #0\n"
        "	strh	r0, [r1]\n"
        "	bl	debug_sub_810D340\n"
        "	mov	r0, #0x1\n"
        "	neg	r0, r0\n"
        "	mov	r1, #0x0\n"
        "	str	r1, [sp]\n"
        "	mov	r2, #0x10\n"
        "	mov	r3, #0x0\n"
        "	bl	BeginNormalPaletteFade\n"
        "	ldr	r0, ._179 + 12\n"
        "	bl	SetVBlankCallback\n"
        "	b	._182\n"
        "._180:\n"
        "	.align	2, 0\n"
        "._179:\n"
        "	.word	0x4000008\n"
        "	.word	0x9f08\n"
        "	.word	0x801\n"
        "	.word	sub_80F8F18+1\n"
        "._156:\n"
        "	bl	UpdatePaletteFade\n"
        "	lsl	r0, r0, #0x18\n"
        "	cmp	r0, #0\n"
        "	beq	._181	@cond_branch\n"
        "	b	._182\n"
        "._157:\n"
        "	ldr	r0, ._183\n"
        "	mov	r1, #0x0\n"
        "	bl	CreateTask\n"
        "	ldr	r0, ._183 + 4\n"
        "	bl	SetMainCallback2\n"
        "._182:\n"
        "	ldr	r1, ._183 + 8\n"
        "	ldr	r0, ._183 + 12\n"
        "	add	r1, r1, r0\n"
        "	ldrb	r0, [r1]\n"
        "	add	r0, r0, #0x1\n"
        "	strb	r0, [r1]\n"
        "._181:\n"
        "	add	sp, sp, #0x8\n"
        "	pop	{r4}\n"
        "	pop	{r0}\n"
        "	bx	r0\n"
        "._184:\n"
        "	.align	2, 0\n"
        "._183:\n"
        "	.word	debug_sub_810CE1C+1\n"
        "	.word	debug_sub_810CDE0+1\n"
        "	.word	gMain\n"
        "	.word	0x43c\n"
        "\n"
    );
}

