set(TILESETDIR data/tilesets)

POKE_GFX_TILES(	${TILESETDIR}/secondary/petalburg/tiles.4bpp					${TILESETDIR}/secondary/petalburg/tiles.png						159	)
POKE_GFX_TILES(	${TILESETDIR}/secondary/rustboro/tiles.4bpp						${TILESETDIR}/secondary/rustboro/tiles.png						498	)
POKE_GFX_TILES(	${TILESETDIR}/secondary/dewford/tiles.4bpp						${TILESETDIR}/secondary/dewford/tiles.png						343	)
POKE_GFX_TILES(	${TILESETDIR}/secondary/slateport/tiles.4bpp					${TILESETDIR}/secondary/slateport/tiles.png						504	)
POKE_GFX_TILES(	${TILESETDIR}/secondary/mauville/tiles.4bpp						${TILESETDIR}/secondary/mauville/tiles.png						450	)
POKE_GFX_TILES(	${TILESETDIR}/secondary/lavaridge/tiles.4bpp					${TILESETDIR}/secondary/lavaridge/tiles.png						348	)
POKE_GFX_TILES(	${TILESETDIR}/secondary/fallarbor/tiles.4bpp					${TILESETDIR}/secondary/fallarbor/tiles.png						374	)
POKE_GFX_TILES(	${TILESETDIR}/secondary/fortree/tiles.4bpp						${TILESETDIR}/secondary/fortree/tiles.png						493	)
POKE_GFX_TILES(	${TILESETDIR}/secondary/mossdeep/tiles.4bpp						${TILESETDIR}/secondary/mossdeep/tiles.png						499	)
POKE_GFX_TILES(	${TILESETDIR}/secondary/pacifidlog/tiles.4bpp					${TILESETDIR}/secondary/pacifidlog/tiles.png					504	)
POKE_GFX_TILES(	${TILESETDIR}/secondary/sootopolis/tiles.4bpp					${TILESETDIR}/secondary/sootopolis/tiles.png					180	)
POKE_GFX_TILES(	${TILESETDIR}/primary/building/tiles.4bpp						${TILESETDIR}/primary/building/tiles.png						502	)
POKE_GFX_TILES(	${TILESETDIR}/secondary/shop/tiles.4bpp							${TILESETDIR}/secondary/shop/tiles.png							502	)
POKE_GFX_TILES(	${TILESETDIR}/secondary/pokemon_center/tiles.4bpp				${TILESETDIR}/secondary/pokemon_center/tiles.png				478	)
POKE_GFX_TILES(	${TILESETDIR}/secondary/cave/tiles.4bpp							${TILESETDIR}/secondary/cave/tiles.png							420	)
POKE_GFX_TILES(	${TILESETDIR}/secondary/pokemon_school/tiles.4bpp				${TILESETDIR}/secondary/pokemon_school/tiles.png				278	)
POKE_GFX_TILES(	${TILESETDIR}/secondary/pokemon_fan_club/tiles.4bpp				${TILESETDIR}/secondary/pokemon_fan_club/tiles.png				319	)
POKE_GFX_TILES(	${TILESETDIR}/secondary/unused_1/tiles.4bpp						${TILESETDIR}/secondary/unused_1/tiles.png						17	)
POKE_GFX_TILES(	${TILESETDIR}/secondary/meteor_falls/tiles.4bpp					${TILESETDIR}/secondary/meteor_falls/tiles.png					422	)
POKE_GFX_TILES(	${TILESETDIR}/secondary/oceanic_museum/tiles.4bpp				${TILESETDIR}/secondary/oceanic_museum/tiles.png				319	)
POKE_GFX_TILES(	${TILESETDIR}/secondary/cable_club/unknown_tiles.4bpp			${TILESETDIR}/secondary/cable_club/unknown_tiles.png			120	)
POKE_GFX_TILES(	${TILESETDIR}/secondary/seashore_house/tiles.4bpp				${TILESETDIR}/secondary/seashore_house/tiles.png				312	)
POKE_GFX_TILES(	${TILESETDIR}/secondary/pretty_petal_flower_shop/tiles.4bpp		${TILESETDIR}/secondary/pretty_petal_flower_shop/tiles.png		345	)
POKE_GFX_TILES(	${TILESETDIR}/secondary/pokemon_day_care/tiles.4bpp				${TILESETDIR}/secondary/pokemon_day_care/tiles.png				355	)
POKE_GFX_TILES(	${TILESETDIR}/secondary/facility/tiles.4bpp						${TILESETDIR}/secondary/facility/tiles.png						503	)
POKE_GFX_TILES(	${TILESETDIR}/secondary/secret_base/brown_cave/tiles.4bpp		${TILESETDIR}/secondary/secret_base/brown_cave/tiles.png		83	)
POKE_GFX_TILES(	${TILESETDIR}/secondary/secret_base/tree/tiles.4bpp				${TILESETDIR}/secondary/secret_base/tree/tiles.png				83	)
POKE_GFX_TILES(	${TILESETDIR}/secondary/secret_base/shrub/tiles.4bpp			${TILESETDIR}/secondary/secret_base/shrub/tiles.png				83	)
POKE_GFX_TILES(	${TILESETDIR}/secondary/secret_base/blue_cave/tiles.4bpp		${TILESETDIR}/secondary/secret_base/blue_cave/tiles.png			83	)
POKE_GFX_TILES(	${TILESETDIR}/secondary/secret_base/yellow_cave/tiles.4bpp		${TILESETDIR}/secondary/secret_base/yellow_cave/tiles.png		83	)
POKE_GFX_TILES(	${TILESETDIR}/secondary/secret_base/red_cave/tiles.4bpp			${TILESETDIR}/secondary/secret_base/red_cave/tiles.png			83	)
POKE_GFX_TILES(	${TILESETDIR}/secondary/inside_of_truck/tiles.4bpp				${TILESETDIR}/secondary/inside_of_truck/tiles.png				62	)
POKE_GFX_TILES(	${TILESETDIR}/secondary/contest/tiles.4bpp						${TILESETDIR}/secondary/contest/tiles.png						430	)
POKE_GFX_TILES(	${TILESETDIR}/secondary/lilycove_museum/tiles.4bpp				${TILESETDIR}/secondary/lilycove_museum/tiles.png				431	)
POKE_GFX_TILES(	${TILESETDIR}/secondary/lab/tiles.4bpp							${TILESETDIR}/secondary/lab/tiles.png							500	)
POKE_GFX_TILES(	${TILESETDIR}/secondary/underwater/tiles.4bpp					${TILESETDIR}/secondary/underwater/tiles.png					500	)
POKE_GFX_TILES(	${TILESETDIR}/secondary/generic_building/tiles.4bpp				${TILESETDIR}/secondary/generic_building/tiles.png				509	)
POKE_GFX_TILES(	${TILESETDIR}/secondary/mauville_game_corner/tiles.4bpp			${TILESETDIR}/secondary/mauville_game_corner/tiles.png			469	)
POKE_GFX_TILES(	${TILESETDIR}/secondary/unused_2/tiles.4bpp						${TILESETDIR}/secondary/unused_2/tiles.png						150	)
POKE_GFX_TILES(	${TILESETDIR}/secondary/rustboro_gym/tiles.4bpp					${TILESETDIR}/secondary/rustboro_gym/tiles.png					94	)
POKE_GFX_TILES(	${TILESETDIR}/secondary/dewford_gym/tiles.4bpp					${TILESETDIR}/secondary/dewford_gym/tiles.png					88	)
POKE_GFX_TILES(	${TILESETDIR}/secondary/lavaridge_gym/tiles.4bpp				${TILESETDIR}/secondary/lavaridge_gym/tiles.png					70	)
POKE_GFX_TILES(	${TILESETDIR}/secondary/fortree_gym/tiles.4bpp					${TILESETDIR}/secondary/fortree_gym/tiles.png					84	)
POKE_GFX_TILES(	${TILESETDIR}/secondary/mossdeep_gym/tiles.4bpp					${TILESETDIR}/secondary/mossdeep_gym/tiles.png					122	)
POKE_GFX_TILES(	${TILESETDIR}/secondary/sootopolis_gym/tiles.4bpp				${TILESETDIR}/secondary/sootopolis_gym/tiles.png				484	)
POKE_GFX_TILES(	${TILESETDIR}/secondary/trick_house_puzzle/tiles.4bpp			${TILESETDIR}/secondary/trick_house_puzzle/tiles.png			255	)
POKE_GFX_TILES(	${TILESETDIR}/secondary/ship/tiles.4bpp							${TILESETDIR}/secondary/ship/tiles.png							342	)
POKE_GFX_TILES(	${TILESETDIR}/secondary/elite_four/tiles.4bpp					${TILESETDIR}/secondary/elite_four/tiles.png					505	)

# reproduce overflow quirk
POKE_GFX_OVERFLOW(	${TILESETDIR}/secondary/pokemon_school/tiles.4bpp.lz			10	)
POKE_GFX_OVERFLOW(	${TILESETDIR}/secondary/pokemon_fan_club/tiles.4bpp.lz			12	)
POKE_GFX_OVERFLOW(	${TILESETDIR}/secondary/pretty_petal_flower_shop/tiles.4bpp.lz	8	)
POKE_GFX_OVERFLOW(	${TILESETDIR}/secondary/pokemon_day_care/tiles.4bpp.lz			14	)
POKE_GFX_OVERFLOW(	${TILESETDIR}/secondary/inside_of_truck/tiles.4bpp.lz			10	)
POKE_GFX_OVERFLOW(	${TILESETDIR}/secondary/battle_tower/tiles.4bpp.lz				16	)

# unused copies of secret base tiles
POKE_GFX_TILES(	${TILESETDIR}/secondary/secret_base/brown_cave/unused_tiles.4bpp	${TILESETDIR}/secondary/secret_base/brown_cave/tiles.png	82	)
POKE_GFX_TILES(	${TILESETDIR}/secondary/secret_base/tree/unused_tiles.4bpp			${TILESETDIR}/secondary/secret_base/tree/tiles.png			82	)
POKE_GFX_TILES(	${TILESETDIR}/secondary/secret_base/shrub/unused_tiles.4bpp			${TILESETDIR}/secondary/secret_base/shrub/tiles.png			82	)
POKE_GFX_TILES(	${TILESETDIR}/secondary/secret_base/blue_cave/unused_tiles.4bpp		${TILESETDIR}/secondary/secret_base/blue_cave/tiles.png		82	)
POKE_GFX_TILES(	${TILESETDIR}/secondary/secret_base/yellow_cave/unused_tiles.4bpp	${TILESETDIR}/secondary/secret_base/yellow_cave/tiles.png	82	)
POKE_GFX_TILES(	${TILESETDIR}/secondary/secret_base/red_cave/unused_tiles.4bpp		${TILESETDIR}/secondary/secret_base/red_cave/tiles.png		82	)
